package jm.task.core.jdbc;


import jm.task.core.jdbc.dao.UserDaoHibernateImpl;
import jm.task.core.jdbc.dao.UserDaoJDBCImpl;
import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

public class Main {

    //private static final Logger logger = Logger.getLogger(Main.class.getName());

    public static void main(String[] args) throws SQLException, IOException {

        UserDaoHibernateImpl userDaoHibernate = new UserDaoHibernateImpl(Util.getSessionFactory());

        UserDaoJDBCImpl userDAO = new UserDaoJDBCImpl();

        userDAO.dropUsersTable();
        userDAO.createUsersTable();

        userDAO.saveUser("Jamaldi", "Danavruzov", (byte) 29);
        userDAO.saveUser("Kamal", "Firsov", (byte) 24);
        userDAO.saveUser("Max", "Korobeinikov", (byte) 15);
        userDAO.saveUser("Roman", "Melonov", (byte) 18);
//
//        List<User> users = userDaoHibernate.getAllUsers();
//        System.out.println("\nВсе пользователи:");
//        for (User u : users) {
//            System.out.println(u);
//        }
//
//        userDAO.cleanUsersTable();
//
//        userDAO.dropUsersTable();
//
//        SessionManager.testConnection();

//        UserDaoHibernateImpl userDaoHibernate = new UserDaoHibernateImpl(SessionManager.getSessionFactory());
//
//        userDaoHibernate.createUsersTable();


    }

//    private static void saveImage() throws SQLException, IOException {
//
//        var sql = """
//                UPDATE users
//                SET image = ?
//                where id = 1
//                """;
//        try (var connection = ConnectionManager.open();
//             var preparedStatement = connection.prepareStatement(sql)) {
//
//            preparedStatement.setBytes(1, Files.readAllBytes(Path.of("C:\\Users\\admin\\IdeaProjects\\jdbc_project_zadanie_1\\Task-1-master\\src\\main\\resources", "Leonid.jpg")));
//            preparedStatement.executeUpdate();
//        }
//    }
//
//    public static void checkMetaData() throws SQLException {
//        try (var connection = ConnectionManager.open()) {
//            var metaData = connection.getMetaData();
//            var catalogs = metaData.getCatalogs();
//            var schemas = metaData.getSchemas();
//            // Курсор, который ходит по перечню наших каталогов
//            while (catalogs.next()) {
//                System.out.println(catalogs.getString(1));
//            }
//            while (schemas.next()) {
//                System.out.println("---------");
//                System.out.println(schemas.getString(1));
//            }
//        }
//    }
//
//    private static List<Integer> getAgeById(int id) throws SQLException {
//
//                SELECT age
//                FROM users
//                where id = ?
//                """;
//        try (var connection = ConnectionManager.open()) {
//
//        }
//
//        List<Integer> result = new ArrayList<>();
//        try (var connection = ConnectionManager.open();
//             var preparedStatement = connection.prepareStatement(sql)) {
//            preparedStatement.setObject(1, id);
//            preparedStatement.setQueryTimeout(10);
//
//            var resultSet = preparedStatement.executeQuery();
//
//            while (resultSet.next()) {
//                // result.add(resultSet.getInt("id"));
//                result.add(resultSet.getObject("age", Integer.class));
//                // Если есть вероятность, что попадется значение null
//            }
//        }
//        return result;
// }
}


// create TABLE IF not EXISTS users (
//                    id SERIAL PRIMARY KEY,
//                    sex varchar(128),
//                    age integer not null,
//                    first_name varchar(128),
//                    last_name varchar(128)
//                );

//insert into users(sex, age, first_name, last_name)
//
//values ('man', 18, 'Miha', 'Shevnin'),
//                        ('woman', 28, 'Dima', 'Pokrov'),
//                                ('man', 15, 'Seva', 'Zavarkin');

//while (executeResult.next()) {
//        System.out.println(executeResult.getInt("id"));
//        System.out.println(executeResult.getString("sex"));
//        System.out.println(executeResult.getString("first_name"));
//        System.out.println(executeResult.getString("last_name"));
//        System.out.println("--------------------");
//            }


//String sql = """
//                insert into users(first_name, age)
//                values ('autogenerated', 20)
//                """;
//
//Class<Driver> driverClass = Driver.class;
//        try (var connection = ConnectionManager.open();
//var statement = connection.createStatement
//        (ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);) {
//        System.out.println(connection.getTransactionIsolation());
//var executeResult = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
//var generatedKeys = statement.getGeneratedKeys();
//
//            if (generatedKeys.next()) {
//var generatedId = generatedKeys.getInt(1);
//                System.out.println(generatedId);
//            }
//
//
//                    }