db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=1488

type=jdbc

#Конфигурация источника данных (Data source)

hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/postgres
hibernate.connection.username=postgres
hibernate.connection.password=1488

#Конфигурация hibernate

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Это нужно, чтобы хибер знал, к какой базе данных
#надо писать sql запросы

hibernate.show_sql=true
#В консоли будет показываться тот sql, который хибер генерирует

hibernate.current_session_context_class=thread